config/routes.rb
Rails.application.routes.draw do

  root "customer/items#top"
  get "/about" => "customer/items#about"

  scope module: :customer do
    resources :addresses
    get "orders/complete" => "orders#complete"
    get "orders/confirm" => "orders#redirect_order_new"
    resources :orders,only:[:new,:create, :index, :show]
    post "orders/confirm"
    delete 'cart_items/all_destroy' => 'cart_items#all_destroy'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :items ,only:[:index,:show] do
      collection do
        post :search_items
      end
    end
    resources :genres, only:[:show]
    resource :customers, only: [:show, :edit, :update]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
  end

  devise_for :customer,skip: [:passwords],controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
  }


 devise_for :administrator, skip: [:registrations, :passwords] ,controllers: {
  sessions: "administrator/sessions"
 }

  namespace :administrator do
    resources :orders ,only:[:index,:show,:update] do
      collection do
        post :order_status
      end
    end
    resources :order_items,only:[:update]
    resources :customers, only: [:index,:show,:edit,:update] do
      member do
        get :search_orders
      end
    end
    resources :genres, only: [:index,:create,:edit,:update]
    resources :items ,only: [:index,:show,:new,:edit,:create,:update] do
      collection do
        post :search_items
      end
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/administrator/customers_controller.rb
class Administrator::CustomersController < ApplicationController
  before_action :authenticate_administrator!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を変更しました"
      redirect_to administrator_customer_path
    else
      render :edit
    end
  end

  def search_orders
    @customer=Customer.find(params[:id])
    @orders=@customer.orders.page(params[:page])
  end

  private
   def customer_params
     params.require(:customer).permit(:last_name,:first_name,:kana_last_name,:kana_first_name,:email,:postal_code,:address,:phone_namber,:encrypted_password,:is_deleted)
   end
end

app/controllers/administrator/orders_controller.rb
class Administrator::OrdersController < ApplicationController
  before_action :authenticate_administrator!
  def index
    # 優先度の高い順に表示する（order_statusと注文日）
    @orders=Order.priority.page(params[:page])
  end

  def show
    @order=Order.find(params[:id])
  end

  def update
    # binding.pry
    order=Order.find(params[:id])
    if order.update(order_status_update_params)
      flash[:notice] = "注文ステータスを更新しました"
      if order.order_status=="payment_clear"
        order.order_items.each do |order_item|
          order_item.update(puroduction_status: "wait_for_start")
          flash[:notice] = "製作ステータスを更新しました"
      end
      end
      redirect_to administrator_order_path(order)
    end
  end

  def order_status
    # binding.pry
    @orders=Order.all.where(order_status: params[:order_status]).page(params[:page])
  end

  private

  def order_status_update_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController
  before_action :authenticate_customer!

  def index
    @address = Address.new
    @addresses = current_customer.addresses
  end

  def edit
    @address = Address.find(params[:id])
  end

  def create
   @address = Address.new(address_params)
   @address.customer_id = current_customer.id
    if @address.save
      flash[:complete]="新規配送先を登録しました"
      redirect_to addresses_path
    else
        @addresses = Address.all
      render :index
    end
  end


   def destroy
   @address =  Address.find(params[:id])
   @address.destroy
   redirect_to addresses_path
   end

   def update
    @address =  Address.find(params[:id])
    if @address.update(address_params)
     flash[:complete]="配送先を変更しました"
     redirect_to addresses_path
    else
     render :edit
    end
   end


  private

  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_items =  current_customer.cart_items.all
    # binding.pry
    @sum = 0
  end

  def create
    # binding.pry
    @cart_item = CartItem.new(cart_item_params)
    if cart_item = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id])
      # binding.pry
       cart_item.quantity += params[:cart_item][:quantity].to_i
       cart_item.save
      flash[:notice] = "カートに商品を追加しました"
      redirect_to cart_items_path
    elsif
     @cart_item.customer_id=current_customer.id
     @cart_item.save
     flash[:notice] = "カートに商品を追加しました"
     redirect_to cart_items_path
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    flash[:notice] = "個数を変更しました"
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:complete]="商品を削除しました"
    redirect_to cart_items_path
  end

  def all_destroy
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    flash[:complete]="カートを空にしました"
    redirect_to cart_items_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity, :item_id)
  end

end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def show
    @customer = current_customer
  end

  def unsubscribe
    @customer = Customer.find_by(email: params[:email])
  end

  def withdrawal
    @customer = Customer.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer =  current_customer
    if @customer.update(customer_params)
     flash[:complete]="編集を変更しました"
     redirect_to customers_path(current_customer)
    else
     render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :phone_namber, :email)
  end


end

app/controllers/customer/genres_controller.rb
class Customer::GenresController < ApplicationController
  def show
    @genres=Genre.all
    @genre=Genre.find(params[:id])
    @items_all_count=@genre.items.is_sales.all.count
    @items=@genre.items.is_sales.page(params[:page])
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  def index
    @items_all_count=Item.is_sales.all.count
    @items= Item.is_sales.page(params[:page])
    @genres= Genre.all
  end

  def show
    @item=Item.find(params[:id])
    @genres = Genre.all
  end

  def search_items
    # binding.pry
    @item_name=params[:query]
    @items=Item.is_sales.where("name LIKE ?", "%#{@item_name}%").page(params[:page])
    @items_all_count=Item.is_sales.where("name LIKE ?", "%#{@item_name}%").count
    @genres=Genre.all
  end

  def top
    @genres = Genre.all
    @item = Item.first(4)
  end

  def about
  end

end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action:authenticate_customer!
  # カートアイテムを1つ以上持っていないと注文できないようにするリダイレクト処理
  before_action:ensure_cart_item ,only:[:new,:comfirm,:create]

  def new
    @order=Order.new()
  end

  def confirm
    # binding.pry
    @order=Order.new()
    # 入力内容の充足チェック#1(支払い方法)
    if @order.cash_mean=confirm_params[:cash_mean]
      # 入力内容の充足チェック#1(お届け先)
      if send_place=confirm_params[:send_place]
        if send_place=="ご自身の住所"
          @order.postal_code=current_customer.postal_code
          @order.address=current_customer.address
          @order.send_name=current_customer.full_name
        elsif send_place=="登録済住所から選択"
          address=current_customer.addresses.find(confirm_params[:address_id])
          @order.postal_code=address.postal_code
          @order.address=address.address
          @order.send_name=address.name
        elsif send_place=="新しいお届け先"
          # 新しいお届け先入力確認
          unless (confirm_params[:new_postal_code]=="") || (confirm_params[:new_address]=="") || (confirm_params[:new_name]=="")
            @order.postal_code=confirm_params[:new_postal_code]
            @order.address=confirm_params[:new_address]
            @order.send_name=confirm_params[:new_name]
          else
            flash[:alert] = "新しいお届け先を入力してください"
            redirect_to new_order_path
          end
        end
      else
        redirect_to new_order_path
        flash[:alert] = "お届け先を選択してください"
      end
    else
      redirect_to new_order_path
      flash[:alert] = "支払い方法を選択してください"
    end
    # 送料800円
    @order.send_money=800
    # 購入者のidを代入
    @order.customer_id=current_customer.id
    # 商品合計金額
    @total=current_customer.buynow_total
    # 請求金額の代入
    @order.total_money=@total+800
  end

  def create
    # binding.pry
    order=Order.create(create_params)
    cart_items=CartItem.where(customer_id: current_customer.id)
    cart_items.each do |cart_item|
      order_item=OrderItem.new()
      order_item.item_id=cart_item.item.id
      order_item.order_id=order.id
      order_item.quantity=cart_item.quantity
      order_item.intax_price=cart_item.item.with_tax_price
      order_item.save
      cart_item.destroy
    end
    redirect_to orders_complete_path
  end

  def complete
  end

  def redirect_order_new
    redirect_to new_order_path
  end


  def index
    @orders = current_customer.orders.order(created_at: :desc).page(params[:page])
  end

  def show
    @order = Order.find(params[:id])
    @order_item = @order.order_items
    @order.send_money=800
  end


 private

  def confirm_params
    params.require(:order).permit(:new_send_name,:new_postal_code,:new_address,:cash_mean,:address_id,:send_place)
  end

  def create_params
    params.require(:order).permit(:customer_id,:send_name,:total_money,:cash_mean,:postal_code,:address,:order_status)
  end

  def ensure_cart_item
    # binding.pry
    unless current_customer.cart_items.count >=1
      # binding.pry
      flash[:alert]="商品をカートに入れてください"
      redirect_to cart_items_path
    end
  end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     customers_path
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  before_action :customer_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]
  protected
 # 退会しているかを判断するメソッド
  def customer_state
    ## 【処理内容1】 入力されたemailからアカウントを1件取得
    @customer = Customer.find_by(email: params[:customer][:email])
    ## アカウントを取得できなかった場合、このメソッドを終了する
    return if !@customer
    ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
    if @customer
      if (@customer.valid_password?(params[:customer][:password])&& (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else

    end
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def unsubscribe
    @customer = Customer.find_by(email: params[:email])
  end

  def withdrawal
    @customer = Customer.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to new_customer_registration_path
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer =  Customer.find(params[:id])
    if @customer.update(customer_params)
     flash[:complete]="編集を変更しました"
     redirect_to customer_path(@customer.id)
    else
     render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :phone_namber, :email)
  end


end

app/helpers/administrator/customers_helper.rb
module Administrator::CustomersHelper
end

app/helpers/administrator/orders_helper.rb
module Administrator::OrdersHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/views/customer/orders/complete.html.erb
<div class="container">
  <div class="row my-5">
    <div class="col my-5">
      <h4 class="text-center">ご注文ありがとうございました!</h4>
      <p class="my-5 text-center "><%= link_to "トップへ戻る" ,root_path, class:"text-dark" %></p>
    </div>
  </div>
</div>

app/views/customer/orders/confirm.html.erb
<div class="container">
  <h2 class="border-bottom mt-3 col-md-3">注文情報の確認</h2>
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-8">
          <table class="table table-bordered ">
            <thead class="bg-light">
              <tr>
                <th>商品名</th>
                <th>単価(税込)</th>
                <th>数量</th>
                <th>小計</th>
              </tr>
            </thead>
            <tbody>
              <% current_customer.cart_items.each do |cart_item| %>
              <tr>
                <td><%= cart_item.item.name %></td>
                <td><%= number_to_currency(cart_item.item.with_tax_price) %></td>
                <td><%= cart_item.quantity %></td>
                <td><%= number_to_currency(cart_item.subtotal)%></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="col-3 mx-3">
          <table class="table table-bordered ">
            <tbody>
              <tr>
                <th>送料</td>
                <td>800</td>
              </tr>
              <tr>
                <th>商品合計</th>
                <td><%= number_to_currency(@total) %></td>
              </tr>
              <tr>
                <th>請求金額合計</th>
                <td><%=  number_to_currency(@order.total_money) %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <th>支払方法 </th>
              <td> <%= Order.cash_means_i18n[@order.cash_mean] %></td>
            </tr>
            <tr>
              <th>お届け先</th>
              <td>
                <%= @order.postal_code %><%= @order.address %><br>
                <%= @order.send_name %>
              </td>
            </tr>
          </tbody>
        </table>
        </div>
      </div>

      <div class="row mx-auto">
        <div class="col justify-content-center align-items-center text-center">
        <%= form_with model: @order,url: orders_path,method: :post do |f| %>
          <%= f.hidden_field :customer_id %>
          <%= f.hidden_field :send_name %>
          <%= f.hidden_field :total_money %>
          <%= f.hidden_field :cash_mean %>
          <%= f.hidden_field :postal_code %>
          <%= f.hidden_field :address %>
          <%= f.hidden_field :order_status,:value=>"payment_waiting" %>
          <%= f.submit "注文を確定する",class: "btn btn-yellow rounded-pill text-white "%>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customer/orders/index.html.erb
 <div class="container">
  <h2 class="border-bottom text-dark text-center col-md-3 mt-3">注文履歴一覧</h2>
   <div class="row">
     <div class="table-responsive">
       <table class="table table-bordered text-nowrap">
        <thead class="thead-light">
         <tr>
          <th scope="col">注文日</th>
          <th scope="col">配送先</th>
          <th scope="col">注文商品</th>
          <th scope="col">支払金額</th>
        　<th scope="col">ステータス</th>
        　<th scope="col">注文詳細</th>
         </tr>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
          <tr>
           <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
           <td><%= order.postal_code %><br>
               <%= order.address %><br>
               <%= order.send_name %>
           </td>
           <td>
             <% order.order_items.each do |order_item| %>
             <%= order_item.item.name %><br>
             <% end %>
           </td>
           <td><%= number_to_currency(order.total_money) %></td>
           <td><%= order.order_status_i18n %></td>
           <td class="text-center"><%=link_to "表示する", order_path(order.id), class: "btn btn-outline-secondary rounded-pill " %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
     </div>
    </div>
 </div>

app/views/customer/orders/new.html.erb
<div class="container">
  <h2 class="border-bottom mt-3 col-md-3 text-center">注文情報入力</h2>
  <div class="row">
    <div class="col-sm-10">
      <%= form_with model: @order,url: orders_confirm_path,method: :post do |f| %>

      <div class="row flex-column mt-5">
        <div class="col"><strong>支払方法</strong></div>
        <div class="col mt-3">
          <ul class="list-group">
            <li class="list-group-item">
              <%= f.radio_button :cash_mean, Order.cash_means.key(0)%>
              <%= f.label  Order.cash_means_i18n[:credit_card] ,class: "my-0"%>
            </li>
            <li class="list-group-item">
              <%= f.radio_button :cash_mean, Order.cash_means.key(1)%>
              <%= f.label Order.cash_means_i18n[:transfer] ,class: "my-0"%>
            </li>
          </ul>
        </div>
      </div>

      <div class="row flex-column my-3">
        <div class="col"><strong>お届け先</strong></div>
        <div class="col mt-3">
          <ul class="list-group">
            <li class="list-group-item">
              <%= f.radio_button :send_place, "ご自身の住所" %><%= f.label "ご自身の住所" %><br>
              <div class="mx-3">
                〒<%= current_customer.postal_code %>&ensp;<%= current_customer.address %><br>
                <%= current_customer.full_name %>
              </div>
            </li>
            <% unless current_customer.addresses.count==0 %>
            <li class="list-group-item">
              <%= f.radio_button :send_place, "登録済住所から選択" %><%= f.label "登録済住所から選択" %><br>
              <div class="mx-3">
                <%= f.select :address_id,options_from_collection_for_select(current_customer.addresses, :id, :address_display) %>
              <div>
            </li>
            <% end %>
            <li class="list-group-item">
              <%= f.radio_button :send_place, "新しいお届け先" %><%= f.label "新しいお届け先" %><br>
              <table class="mx-3">
                <tbody>
                  <tr>
                    <td><%= f.label :new_send_name,"郵便番号（ハイフンなし）" %></td>
                    <td><%= f.number_field :new_send_name,placeholder: "0000000"  %></td>
                  </tr>
                  <tr>
                    <td><%= f.label :new_postal_code,"住所" %></td>
                    <td><%= f.text_field :new_postal_code,size: "70x5",placeholder: "東京都渋谷区代々木神園町０−０" %></td>
                  </tr>
                  <tr>
                    <td><%= f.label :new_address,"宛名" %></td>
                    <td><%= f.text_field :new_address,placeholder: "令和道子" %></td>
                  </tr>
                </tbody>
              </table>
            </li>
          </ul>
        </div>
      </div>
      <div class="row">
        <%= f.submit "確認画面へ進む", class: "btn btn-blue text-white rounded-pill col-md-4 mt-5 mx-auto" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customer/orders/show.html.erb
<div class="container">
  <h2 class="col-md-3 mt-3 border-bottom text-dark text-center ">注文履歴詳細</h2>
  <div class="row">
    <div class="col-md-6 mt-3">
      <h5>注文情報</h5>
      <table class="table table-bordered">
     <tbody>
      <tr>
       <th class="bg-light">注文日</th>
       <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
       <th class="bg-light">配送先</th>
       <td><%= @order.postal_code %><br>
           <%= @order.address %><br>
           <%= @order.send_name %>
       </td>
      </tr>
      <tr>
       <th class="bg-light">支払方法</th>
       <td><%= @order.cash_mean_i18n %></td>
      </tr>
      <tr>
        <th class="bg-light">ステータス</th>
        <td><%= @order.order_status_i18n %></td>
      </tr>
     </tbody>
    </table>
   </div>
    <div class="col-md-4 mt-3">
      <h5>請求情報</h5>
      <table class="table table-bordered">
       <tbody>
        <tr>
         <th class="bg-light">商品合計</th>
         <td><%= number_to_currency(@order.total_money - @order.send_money)%></td>
        </tr>
        <tr>
          <th class="bg-light">配送料</th>
          <td><%= number_to_currency(@order.send_money) %></td>
        </tr>
        <tr>
          <th class="bg-light">ご請求金額</th>
          <td><%= number_to_currency(@order.total_money)%></td>
        </tr>
       </tbody>
      </table>
    </div>
  </div>

  <div class="row">
   <div class="col-md-8 mt-3">
    <h5>注文内容</h5>
    <table class="table table-bordered">
     <thead class="thead-light">
       <tr>
        <th>商品</th>
        <th>単価（税込）</th>
        <th>個数</th>
        <th>小計</th>
       </tr>
     </thead>
     <% @order_item.each do |order_item| %>
     <tbody>
       <tr>
         <td><%= order_item.item.name %></td>
         <td><%= number_to_currency(order_item.intax_price) %></td>
         <td><%= order_item.quantity %></td>
         <td><%= number_to_currency(order_item.subtotal)%></td>
       </tr>
      </tbody>
      <% end %>
     </table>
     </div>
    </div>
 </div>