config/routes.rb
Rails.application.routes.draw do

  root "customer/items#top"
  get "/about" => "customer/items#about"

  scope module: :customer do
    resources :addresses
    get "orders/complete" => "orders#complete"
    get "orders/confirm" => "orders#redirect_order_new"
    resources :orders,only:[:new,:create, :index, :show]
    post "orders/confirm"
    delete 'cart_items/all_destroy' => 'cart_items#all_destroy'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :items ,only:[:index,:show] do
      collection do
        post :search_items
      end
    end
    resources :genres, only:[:show]
    resource :customers, only: [:show, :edit, :update]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
  end

  devise_for :customer,skip: [:passwords],controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
  }


 devise_for :administrator, skip: [:registrations, :passwords] ,controllers: {
  sessions: "administrator/sessions"
 }

  namespace :administrator do
    resources :orders ,only:[:index,:show,:update] do
      collection do
        post :order_status
      end
    end
    resources :order_items,only:[:update]
    resources :customers, only: [:index,:show,:edit,:update] do
      member do
        get :search_orders
      end
    end
    resources :genres, only: [:index,:create,:edit,:update]
    resources :items ,only: [:index,:show,:new,:edit,:create,:update] do
      collection do
        post :search_items
      end
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/administrator/customers_controller.rb
class Administrator::CustomersController < ApplicationController
  before_action :authenticate_administrator!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を変更しました"
      redirect_to administrator_customer_path
    else
      render :edit
    end
  end

  def search_orders
    @customer=Customer.find(params[:id])
    @orders=@customer.orders.page(params[:page])
  end

  private
   def customer_params
     params.require(:customer).permit(:last_name,:first_name,:kana_last_name,:kana_first_name,:email,:postal_code,:address,:phone_namber,:encrypted_password,:is_deleted)
   end
end

app/controllers/administrator/items_controller.rb
class Administrator::ItemsController < ApplicationController
  before_action :authenticate_administrator!

  def index
    @items=Item.page(params[:page])
  end

  def show
    @item=Item.find(params[:id])
  end

  def new
    @item=Item.new()
  end

  def edit
    @item=Item.find(params[:id])
  end

  def create
    # binding.pry
    @item=Item.new(item_params)
    if @item.save
      redirect_to  administrator_item_path(@item)
    else
      #flash[:alert]="全ての項目を入力してください"
      render  new_administrator_item_path
    end
  end

  def search_items
    
    @item_name=params[:query]
    @items=Item.all.where("name LIKE ?", "%#{@item_name}%").page(params[:page])
    @items_all_count=Item.all.where("name LIKE ?", "%#{@item_name}%").count
  end

  def update
    item=Item.find(params[:id])
    # binding.pry
    if item.update(item_params)
      flash[:notice] = "商品詳細を変更しました"
      redirect_to administrator_item_path(item)
    end
  end

  private

  def item_params
    params.require(:item).permit(:image,:name,:explanation,:genre_id,:out_tax_price,:sales_status)
  end

end

app/controllers/customer/addresses_controller.rb
class Customer::AddressesController < ApplicationController
  before_action :authenticate_customer!

  def index
    @address = Address.new
    @addresses = current_customer.addresses
  end

  def edit
    @address = Address.find(params[:id])
  end

  def create
   @address = Address.new(address_params)
   @address.customer_id = current_customer.id
    if @address.save
      flash[:complete]="新規配送先を登録しました"
      redirect_to addresses_path
    else
        @addresses = Address.all
      render :index
    end
  end


   def destroy
   @address =  Address.find(params[:id])
   @address.destroy
   redirect_to addresses_path
   end

   def update
    @address =  Address.find(params[:id])
    if @address.update(address_params)
     flash[:complete]="配送先を変更しました"
     redirect_to addresses_path
    else
     render :edit
    end
   end


  private

  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_items =  current_customer.cart_items.all
    # binding.pry
    @sum = 0
  end

  def create
    # binding.pry
    @cart_item = CartItem.new(cart_item_params)
    if cart_item = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id])
      # binding.pry
       cart_item.quantity += params[:cart_item][:quantity].to_i
       cart_item.save
      flash[:notice] = "カートに商品を追加しました"
      redirect_to cart_items_path
    elsif
     @cart_item.customer_id=current_customer.id
     @cart_item.save
     flash[:notice] = "カートに商品を追加しました"
     redirect_to cart_items_path
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    flash[:notice] = "個数を変更しました"
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:complete]="商品を削除しました"
    redirect_to cart_items_path
  end

  def all_destroy
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    flash[:complete]="カートを空にしました"
    redirect_to cart_items_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity, :item_id)
  end

end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  def show
    @customer = current_customer
  end

  def unsubscribe
    @customer = Customer.find_by(email: params[:email])
  end

  def withdrawal
    @customer = Customer.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer =  current_customer
    if @customer.update(customer_params)
     flash[:complete]="編集を変更しました"
     redirect_to customers_path(current_customer)
    else
     render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :phone_namber, :email)
  end


end

app/controllers/customer/genres_controller.rb
class Customer::GenresController < ApplicationController
  def show
    @genres=Genre.all
    @genre=Genre.find(params[:id])
    @items_all_count=@genre.items.is_sales.all.count
    @items=@genre.items.is_sales.page(params[:page])
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  def index
    @items_all_count=Item.is_sales.all.count
    @items= Item.is_sales.page(params[:page])
    @genres= Genre.all
  end

  def show
    @item=Item.find(params[:id])
    @genres = Genre.all
  end

  def search_items
    # binding.pry
    @item_name=params[:query]
    @items=Item.is_sales.where("name LIKE ?", "%#{@item_name}%").page(params[:page])
    @items_all_count=Item.is_sales.where("name LIKE ?", "%#{@item_name}%").count
    @genres=Genre.all
  end

  def top
    @genres = Genre.all
    @item = Item.first(4)
  end

  def about
  end

end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action:authenticate_customer!
  # カートアイテムを1つ以上持っていないと注文できないようにするリダイレクト処理
  before_action:ensure_cart_item ,only:[:new,:comfirm,:create]

  def new
    @order=Order.new()
  end

  def confirm
    # binding.pry
    @order=Order.new()
    # 入力内容の充足チェック#1(支払い方法)
    if @order.cash_mean=confirm_params[:cash_mean]
      # 入力内容の充足チェック#1(お届け先)
      if send_place=confirm_params[:send_place]
        if send_place=="ご自身の住所"
          @order.postal_code=current_customer.postal_code
          @order.address=current_customer.address
          @order.send_name=current_customer.full_name
        elsif send_place=="登録済住所から選択"
          address=current_customer.addresses.find(confirm_params[:address_id])
          @order.postal_code=address.postal_code
          @order.address=address.address
          @order.send_name=address.name
        elsif send_place=="新しいお届け先"
          # 新しいお届け先入力確認
          unless (confirm_params[:new_postal_code]=="") || (confirm_params[:new_address]=="") || (confirm_params[:new_name]=="")
            @order.postal_code=confirm_params[:new_postal_code]
            @order.address=confirm_params[:new_address]
            @order.send_name=confirm_params[:new_name]
          else
            flash[:alert] = "新しいお届け先を入力してください"
            redirect_to new_order_path
          end
        end
      else
        redirect_to new_order_path
        flash[:alert] = "お届け先を選択してください"
      end
    else
      redirect_to new_order_path
      flash[:alert] = "支払い方法を選択してください"
    end
    # 送料800円
    @order.send_money=800
    # 購入者のidを代入
    @order.customer_id=current_customer.id
    # 商品合計金額
    @total=current_customer.buynow_total
    # 請求金額の代入
    @order.total_money=@total+800
  end

  def create
    # binding.pry
    order=Order.create(create_params)
    cart_items=CartItem.where(customer_id: current_customer.id)
    cart_items.each do |cart_item|
      order_item=OrderItem.new()
      order_item.item_id=cart_item.item.id
      order_item.order_id=order.id
      order_item.quantity=cart_item.quantity
      order_item.intax_price=cart_item.item.with_tax_price
      order_item.save
      cart_item.destroy
    end
    redirect_to orders_complete_path
  end

  def complete
  end

  def redirect_order_new
    redirect_to new_order_path
  end


  def index
    @orders = current_customer.orders.order(created_at: :desc).page(params[:page])
  end

  def show
    @order = Order.find(params[:id])
    @order_item = @order.order_items
    @order.send_money=800
  end


 private

  def confirm_params
    params.require(:order).permit(:new_send_name,:new_postal_code,:new_address,:cash_mean,:address_id,:send_place)
  end

  def create_params
    params.require(:order).permit(:customer_id,:send_name,:total_money,:cash_mean,:postal_code,:address,:order_status)
  end

  def ensure_cart_item
    # binding.pry
    unless current_customer.cart_items.count >=1
      # binding.pry
      flash[:alert]="商品をカートに入れてください"
      redirect_to cart_items_path
    end
  end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     customers_path
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  before_action :customer_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]
  protected
 # 退会しているかを判断するメソッド
  def customer_state
    ## 【処理内容1】 入力されたemailからアカウントを1件取得
    @customer = Customer.find_by(email: params[:customer][:email])
    ## アカウントを取得できなかった場合、このメソッドを終了する
    return if !@customer
    ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
    if @customer
      if (@customer.valid_password?(params[:customer][:password])&& (@customer.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else

    end
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end

  def unsubscribe
    @customer = Customer.find_by(email: params[:email])
  end

  def withdrawal
    @customer = Customer.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to new_customer_registration_path
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer =  Customer.find(params[:id])
    if @customer.update(customer_params)
     flash[:complete]="編集を変更しました"
     redirect_to customer_path(@customer.id)
    else
     render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :postal_code, :address, :phone_namber, :email)
  end


end

app/helpers/administrator/customers_helper.rb
module Administrator::CustomersHelper
end

app/helpers/administrator/items_helper.rb
module Administrator::ItemsHelper
end

app/helpers/customer/addresses_helper.rb
module Customer::AddressesHelper
end

app/views/customer/items/_genre.html.erb
<div class="card">
  <h5 class="card-header text-center bg-white">ジャンル検索</h5>
    <div class="h-75 card-body">
      <% genres.each do |genre| %>
      <div class="my-4">
        <%= link_to genre_path(genre.id) do %>
          <p class="text-dark"><%= genre.genre_name %></p>
        <% end %>
      </div>
      <% end %>
    </div>
</div>

app/views/customer/items/about.html.erb
<div class="main-container d-flex align-items-center pb-5">
  <div class=" text-yellow offset-1">
    <h4>産地直送、新鮮な材料を使用！<br>
        旬のフルーツとこだわりのクリーム
    </h4>
    <h2 class="offset-2">Nagano Cake</h2>
  </div>
</div>

app/views/customer/items/index.html.erb
<div class="container mb-5">
  <h2 class="mb-5 mt-5">商品一覧<span>（全<%= @items_all_count %>件）</span></h2>
    <div class='row px-md-0 ml-2 mt-5'>
      <div class='col-md-3 mx-auto mb-3'>
        <%= render "genre", genres: @genres %>
      </div>
      <div class='col-md-9 justify-content-end'>
        <div class='row mb-5'>
          <% @items.each do |item| %>
            <div class='card mx-1 border border-0 mr-3'>
               <%= link_to item_path(item) do %>
                 <%= image_tag item.get_image ,size: "240x160"%>
               <% end %>
               <%= link_to item_path(item) do %>
                 <p class="text-secondary mt-1 mb-0"><%= item.name %></p>
               <% end %>
               <p class="text-secondary"><%= number_to_currency(item.with_tax_price) %></p>
            </div>
          <% end %>
        </div>
        <div class="text-center mx-auto">
         <%= paginate @items %>
        </div>
      </div>
    </div>
</div>

app/views/customer/items/search_items.html.erb
<div class="container mb-5">
  <h2 class="mb-5 mt-5">"<%= @item_name %>"検索結果一覧<span>（全<%= @items_all_count %>件）</span></h2>
  <div class='row px-md-0 ml-2 mt-5'>
    <div class='col-md-3 mx-auto mb-3'>
      <%= render "customer/items/genre", genres: @genres %>
    </div>
    <div class='col-md-9 justify-content-end'>
      <div class='row mb-5'>
        <% @items.each do |item| %>
          <div class='card mx-1 border border-0 mr-3'>
             <%= link_to item_path(item) do %>
              <%= image_tag item.get_image ,size: "240x160"%>
             <% end %>
             <%= link_to item_path(item) do %>
             <p class="text-secondary mt-1 mb-0"><%= item.name %></p>
             <% end %>
             <p class="text-secondary"><%= number_to_currency(item.with_tax_price) %></p>
          </div>
         <% end %>
      </div>
      <div class="text-center mx-auto">
        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/customer/items/show.html.erb
<div class='row px-3 px-sm-0  mt-5'>
  <div class="col-sm-2 mx-auto my-2">
    <%= render "genre", genres: @genres %>
  </div>
  <div class=" d-block mx-auto my-2">
    <%= image_tag @item.get_image, size: "auto"%>
  </div>

  <div class='col-sm-4 mx-auto my-2'>
    <h2><%= @item.name %></h2>
    <p class="mt-3"><%= @item.explanation %></p>
    <h3 class="mt-5"><%= number_to_currency(@item.out_tax_price* 1.1)%>（税込）</h3>
      <div class="mt-5">
      <%= form_with model: CartItem.new(),url: cart_items_path,method: :post  do |f| %>
        <%= f.select :quantity,select_box_items(30) %>
        <%= f.hidden_field :item_id,:value =>@item.id %>
        <%= f.submit "カートに入れる",  class: "btn btn-outline-blue ml-5" %>
      <% end %>
      </div>
  </div>
</div>

app/views/customer/items/top.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-lg-3 mt-5">
     <%= render "genre", genres: @genres %>
    </div>
    <div class="col-lg-9 mt-5">
      <div class="row">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= image_tag 'cake18.png',style: "background-size: cover;", size: "850x280" ,class: "carousel_image " %>
              <div class="carousel-caption  d-md-block mb-5">
                <h4 class="card-text text-white mb-5">
                 ようこそNagano Cakeへ！<br>
                 このサイトはOnline Shopです<br>
                 会員でない方も商品の閲覧はできますが<br>
                 購入には会員登録が必要になります
                </h4>
              </div>
            </div>
            <div class="carousel-item">
              <%= image_tag 'cake16.png', size: "850x280" ,class: "carousel_image"%>
            </div>
            <div class="carousel-item">
              <%= image_tag 'cake12.png', size: "850x280" ,class: "carousel_image"%>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
           <span class="carousel-control-prev-icon" aria-hidden="true"></span>
           <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <h2 class="mt-5">新着商品</h2>
      <div class="row">
      <% @item.each do |item| %>
        <div class="my-auto mx-auto">
          <%= link_to item_path(item) do %>
            <%= image_tag item.get_image, size: "210x140", class: "mx-auto d-block" %>
          <% end %>
          <%= link_to item_path(item) do %>
            <p class="text-secondary mt-1 mb-0"><%= item.name %></p>
          <% end %>
          <p class="text-secondary"><%= number_to_currency(item.with_tax_price) %></p>
        </div>
      <% end %>
     </div>
     <div class="text-right">
       <%= link_to "全ての商品を見る >", items_path, class: "btn btn-outline-blue" %>
     </div>
   </div>
  </div>
</div>