config/routes.rb
Rails.application.routes.draw do

  root "customer/items#top"
  get "/about" => "customer/items#about"

  scope module: :customer do
    resources :addresses
    get "orders/complete" => "orders#complete"
    get "orders/confirm" => "orders#redirect_order_new"
    resources :orders,only:[:new,:create, :index, :show]
    post "orders/confirm"
    delete 'cart_items/all_destroy' => 'cart_items#all_destroy'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :items ,only:[:index,:show] do
      collection do
        post :search_items
      end
    end
    resources :genres, only:[:show]
    resource :customers, only: [:show, :edit, :update]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
  end

  devise_for :customer,skip: [:passwords],controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
  }


 devise_for :administrator, skip: [:registrations, :passwords] ,controllers: {
  sessions: "administrator/sessions"
 }

  namespace :administrator do
    resources :orders ,only:[:index,:show,:update] do
      collection do
        post :order_status
      end
    end
    resources :order_items,only:[:update]
    resources :customers, only: [:index,:show,:edit,:update] do
      member do
        get :search_orders
      end
    end
    resources :genres, only: [:index,:create,:edit,:update]
    resources :items ,only: [:index,:show,:new,:edit,:create,:update] do
      collection do
        post :search_items
      end
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/administrator.rb
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  # 支払方法のステータス（cash_mean）の設定
  enum cash_mean:{
    credit_card:0,
    transfer:1
  }

  # 注文ステータス（order_status）の設定
  enum order_status:{
    payment_waiting:0,
    payment_clear:1,
    in_production:2,
    delivery_preparation:3,
    delivery_complete:4
  }

  has_many :order_items, dependent: :destroy
  belongs_to :customer

  # 管理者の注文一覧の並べ替え機能に利用
  scope :priority, -> { order(order_status: :asc,created_at: :asc) }

  # 注文に登録されているデータから宛名を生成する関数
  def address_display
    '〒' + postal_code.to_s + ' ' + address.to_s + ' ' + send_name.to_s
  end

  # 注文に紐つく注文商品の合計金額を算出する関数
  def payment_total
    sum=0
    order_items.each do |order_item|
      sum+=order_item.subtotal
    end
    sum
  end

  # 注文の全商品数を算出する関数
  def count_total
    sum=0
    order_items.each do |order_item|
      sum+=order_item.quantity
    end
    sum
  end

  # 注文に紐つく注文商品群の中から製作中より低いステータス注文商品を取得
  def order_items_minimum_status
    order_items.where("puroduction_status < 3").count
  end
end

app/controllers/administrator/confirmations_controller.rb
# frozen_string_literal: true

class Administrators::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/administrator/customers_controller.rb
class Administrator::CustomersController < ApplicationController
  before_action :authenticate_administrator!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を変更しました"
      redirect_to administrator_customer_path
    else
      render :edit
    end
  end

  def search_orders
    @customer=Customer.find(params[:id])
    @orders=@customer.orders.page(params[:page])
  end

  private
   def customer_params
     params.require(:customer).permit(:last_name,:first_name,:kana_last_name,:kana_first_name,:email,:postal_code,:address,:phone_namber,:encrypted_password,:is_deleted)
   end
end

app/controllers/administrator/genres_controller.rb
class Administrator::GenresController < ApplicationController
 before_action :authenticate_administrator!
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    unless @genre.save
      @genres = Genre.all
      render :error
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
       flash[:notice] = "ジャンルを変更しました"
       redirect_to administrator_genres_path
    else
       flash[:notice] = "ジャンル名を入力してください"
       render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/controllers/administrator/items_controller.rb
class Administrator::ItemsController < ApplicationController
  before_action :authenticate_administrator!

  def index
    @items=Item.page(params[:page])
  end

  def show
    @item=Item.find(params[:id])
  end

  def new
    @item=Item.new()
  end

  def edit
    @item=Item.find(params[:id])
  end

  def create
    # binding.pry
    @item=Item.new(item_params)
    if @item.save
      redirect_to  administrator_item_path(@item)
    else
      #flash[:alert]="全ての項目を入力してください"
      render  new_administrator_item_path
    end
  end

  def search_items
    
    @item_name=params[:query]
    @items=Item.all.where("name LIKE ?", "%#{@item_name}%").page(params[:page])
    @items_all_count=Item.all.where("name LIKE ?", "%#{@item_name}%").count
  end

  def update
    item=Item.find(params[:id])
    # binding.pry
    if item.update(item_params)
      flash[:notice] = "商品詳細を変更しました"
      redirect_to administrator_item_path(item)
    end
  end

  private

  def item_params
    params.require(:item).permit(:image,:name,:explanation,:genre_id,:out_tax_price,:sales_status)
  end

end

app/controllers/administrator/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Administrators::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/administrator/order_items_controller.rb
class Administrator::OrderItemsController < ApplicationController

  def update
    order_item=OrderItem.find(params[:id])
    order=order_item.order
    # 注文の自動更新機能の実装
    if order_item.update(order_item_params)
      # 注文商品のステータスが1つでも製作中になった場合、注文のステータスを製作中に自動更新
      if order_item.puroduction_status=="creating"
        order.update(order_status: "in_production" )
      end
      # 注文商品のステータスが全て製作中になった場合、注文のステータスを製作中に自動更新
      # 注文に紐つく注文商品群の中に2（＝製作中）以下のステータスを持つ商品有無で判定
      if order_item.puroduction_status=="complete"
        unless order.order_items_minimum_status >=1
          order.update(order_status: "delivery_preparation")
        end
      end
      redirect_to administrator_order_path(order_item.order)
    end
  end

  private

  def order_item_params
    params.require(:order_item).permit(:puroduction_status)
  end

end

app/controllers/administrator/orders_controller.rb
class Administrator::OrdersController < ApplicationController
  before_action :authenticate_administrator!
  def index
    # 優先度の高い順に表示する（order_statusと注文日）
    @orders=Order.priority.page(params[:page])
  end

  def show
    @order=Order.find(params[:id])
  end

  def update
    # binding.pry
    order=Order.find(params[:id])
    if order.update(order_status_update_params)
      flash[:notice] = "注文ステータスを更新しました"
      if order.order_status=="payment_clear"
        order.order_items.each do |order_item|
          order_item.update(puroduction_status: "wait_for_start")
          flash[:notice] = "製作ステータスを更新しました"
      end
      end
      redirect_to administrator_order_path(order)
    end
  end

  def order_status
    # binding.pry
    @orders=Order.all.where(order_status: params[:order_status]).page(params[:page])
  end

  private

  def order_status_update_params
    params.require(:order).permit(:order_status)
  end
end

app/controllers/administrator/passwords_controller.rb
# frozen_string_literal: true

class Administrators::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/administrator/registrations_controller.rb
# frozen_string_literal: true

class Administrators::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/administrator/sessions_controller.rb
# frozen_string_literal: true

class Administrator::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :forced_customer_sign_out

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

   protected
     def after_sign_in_path_for(resource)
       administrator_orders_path
     end

     def after_sign_out_path_for(resource)
       administrator_session_path
     end

     def forced_customer_sign_out
        if customer_signed_in?
          sign_out
        end
     end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/administrator/unlocks_controller.rb
# frozen_string_literal: true

class Administrators::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action:authenticate_customer!
  # カートアイテムを1つ以上持っていないと注文できないようにするリダイレクト処理
  before_action:ensure_cart_item ,only:[:new,:comfirm,:create]

  def new
    @order=Order.new()
  end

  def confirm
    # binding.pry
    @order=Order.new()
    # 入力内容の充足チェック#1(支払い方法)
    if @order.cash_mean=confirm_params[:cash_mean]
      # 入力内容の充足チェック#1(お届け先)
      if send_place=confirm_params[:send_place]
        if send_place=="ご自身の住所"
          @order.postal_code=current_customer.postal_code
          @order.address=current_customer.address
          @order.send_name=current_customer.full_name
        elsif send_place=="登録済住所から選択"
          address=current_customer.addresses.find(confirm_params[:address_id])
          @order.postal_code=address.postal_code
          @order.address=address.address
          @order.send_name=address.name
        elsif send_place=="新しいお届け先"
          # 新しいお届け先入力確認
          unless (confirm_params[:new_postal_code]=="") || (confirm_params[:new_address]=="") || (confirm_params[:new_name]=="")
            @order.postal_code=confirm_params[:new_postal_code]
            @order.address=confirm_params[:new_address]
            @order.send_name=confirm_params[:new_name]
          else
            flash[:alert] = "新しいお届け先を入力してください"
            redirect_to new_order_path
          end
        end
      else
        redirect_to new_order_path
        flash[:alert] = "お届け先を選択してください"
      end
    else
      redirect_to new_order_path
      flash[:alert] = "支払い方法を選択してください"
    end
    # 送料800円
    @order.send_money=800
    # 購入者のidを代入
    @order.customer_id=current_customer.id
    # 商品合計金額
    @total=current_customer.buynow_total
    # 請求金額の代入
    @order.total_money=@total+800
  end

  def create
    # binding.pry
    order=Order.create(create_params)
    cart_items=CartItem.where(customer_id: current_customer.id)
    cart_items.each do |cart_item|
      order_item=OrderItem.new()
      order_item.item_id=cart_item.item.id
      order_item.order_id=order.id
      order_item.quantity=cart_item.quantity
      order_item.intax_price=cart_item.item.with_tax_price
      order_item.save
      cart_item.destroy
    end
    redirect_to orders_complete_path
  end

  def complete
  end

  def redirect_order_new
    redirect_to new_order_path
  end


  def index
    @orders = current_customer.orders.order(created_at: :desc).page(params[:page])
  end

  def show
    @order = Order.find(params[:id])
    @order_item = @order.order_items
    @order.send_money=800
  end


 private

  def confirm_params
    params.require(:order).permit(:new_send_name,:new_postal_code,:new_address,:cash_mean,:address_id,:send_place)
  end

  def create_params
    params.require(:order).permit(:customer_id,:send_name,:total_money,:cash_mean,:postal_code,:address,:order_status)
  end

  def ensure_cart_item
    # binding.pry
    unless current_customer.cart_items.count >=1
      # binding.pry
      flash[:alert]="商品をカートに入れてください"
      redirect_to cart_items_path
    end
  end
end

app/helpers/administrator/customers_helper.rb
module Administrator::CustomersHelper
end

app/helpers/administrator/genres_helper.rb
module Administrator::GenresHelper
end

app/helpers/administrator/items_helper.rb
module Administrator::ItemsHelper
end

app/helpers/administrator/order_items_helper.rb
module Administrator::OrderItemsHelper
end

app/helpers/administrator/orders_helper.rb
module Administrator::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/administrator/orders/_lists.html.erb
      <table class="table table-hover">
        <thead class="bg-light">
          <tr>
            <th style="width: 30%">購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% orders.each do |order| %>
          <tr onclick='window.location="<%= administrator_order_path(order) %>"' role="link">
            <td style="width: 30%">
              <p class="text-dark"><%= order.created_at.to_s(:datetime_jp) %></p>
            </td>
            <td>
              <%= order.customer.last_name %><%= order.customer.first_name %>
            </td>
            <td>
              <%= order.count_total %>
            </td>
            <td><%= Order.order_statuses_i18n[order.order_status.to_sym] %></td>
          </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="4" class="text-center" >
              <%= paginate orders %>
            </td>
          </tr>
        </tfoot>
      </table>

app/views/administrator/orders/index.html.erb
<div class="container">
  <h2 class="border-bottom mt-3 col-md-3 text-center">注文履歴一覧</h2>
  <div class="row">
    <div class="col-sm-10 mx-auto my-2">
      <%= form_with url: order_status_administrator_orders_path,method: :post,class: "mb-2 text-right",local: false do |f| %>
        <%= f.select :order_status ,Order.order_statuses.keys.map{|k|[I18n.t("enums.order.order_status.#{k}"),k]},
            class: "form-control"%>
        <%= button_tag :type => "submit", :class =>"btn btn-outline-dark" do %>
          ステータス検索
        <% end %>
      <% end %>
      <div class="order_lists">
        <%= render "administrator/orders/lists", orders: @orders %>
      </div>
    </div>
  </div>
</div>

app/views/administrator/orders/order_status.js.erb
  $(".order_lists").html("<%= j(render  "administrator/orders/lists", orders: @orders) %>");

app/views/administrator/orders/show.html.erb
<div class="container">
  <h2 class="border-bottom mt-3 col-md-3 text-center">注文履歴詳細</span></h2>
  <div class="row">
    <div class="col-sm-12 mx-auto mt-3">
    <table class="table table-borderless ">
      <tbody>
        <tr>
          <th style="width: 20%">購入者</th>
          <td><%= @order.customer.full_name %></td>
        </tr>
        <tr><th style="width: 20% bg-liht">注文日</th><td><%= @order.created_at.to_s(:datetime_jp) %></td></tr>
        <tr><th style="width: 20%">配送先</th><td><%= @order.address_display %><br></td></tr>
        <tr><th style="width: 20%">支払方法</th><td><%= I18n.t("enums.order.cash_mean.#{@order.cash_mean}") %></td></tr>
        <tr>
          <th style="width: 20%">注文ステータス</th>
          <td>
            <%= form_with model: @order,url: administrator_order_path,method: :patch,class: "form-group" do |f|%>
            <%= f.select :order_status,Order.order_statuses.keys.map{|k| [I18n.t("enums.order.order_status.#{k}"),k]} ,
                class: "form-select form-select-lg"%>&nbsp;
            <%= f.submit "更新" ,class: "btn btn-green text-white mx-1"%>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-sm-7  position-relative">
      <table class="table">
      <thead class="table-light">
      <tr>
        <th class="bg-light">商品名</th>
        <th class="bg-light">単価（税込）</th>
        <th class="bg-light">数量</th>
        <th class="bg-light">小計</th>
        <th class="bg-light">製作ステータス</th>
      </tr>
      </thead>
      <tbody>
        <% @order.order_items.each do |order_item| %>
        <tr>
          <td><%= order_item.item.name %></td>
          <td><%= number_to_currency(order_item.intax_price) %></td>
          <td><%= order_item.quantity %></td>
          <td><%= number_to_currency(order_item.subtotal) %></td>
          <td>
          <%= form_with model: order_item,url: administrator_order_item_path(order_item),method: :patch do |f| %>
            <%= f.select :puroduction_status,OrderItem.puroduction_statuses.keys.map{|k| [I18n.t("enums.order_item.puroduction_status.#{k}"),k]},
                selected: order_item.puroduction_status %>&nbsp;
            <%= f.submit "更新",class: "btn btn-green text-white mx-1" %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    <div class="col-sm-4 offset-sm-1 align-self-end">
    <div>
      <table class="table table-border">
        <tr><th class="bg-light">商品合計</th><td><%= number_to_currency(@order.payment_total) %></td></tr>
        <tr><th class="bg-light">送料</th><td>800円</td></tr>
        <tr><th class="bg-light">請求金額合計</th><td><% all_payment=@order.payment_total+800 %><%= number_to_currency(all_payment)%></td></tr>
      </table>
    </div>
    </div>
  </div>
</div>