config/routes.rb
Rails.application.routes.draw do

  root "customer/items#top"
  get "/about" => "customer/items#about"

  scope module: :customer do
    resources :addresses
    get "orders/complete" => "orders#complete"
    get "orders/confirm" => "orders#redirect_order_new"
    resources :orders,only:[:new,:create, :index, :show]
    post "orders/confirm"
    delete 'cart_items/all_destroy' => 'cart_items#all_destroy'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    resources :items ,only:[:index,:show] do
      collection do
        post :search_items
      end
    end
    resources :genres, only:[:show]
    resource :customers, only: [:show, :edit, :update]
    get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
  end

  devise_for :customer,skip: [:passwords],controllers: {
  registrations: "customer/registrations",
  sessions: 'customer/sessions'
  }


 devise_for :administrator, skip: [:registrations, :passwords] ,controllers: {
  sessions: "administrator/sessions"
 }

  namespace :administrator do
    resources :orders ,only:[:index,:show,:update] do
      collection do
        post :order_status
      end
    end
    resources :order_items,only:[:update]
    resources :customers, only: [:index,:show,:edit,:update] do
      member do
        get :search_orders
      end
    end
    resources :genres, only: [:index,:create,:edit,:update]
    resources :items ,only: [:index,:show,:new,:edit,:create,:update] do
      collection do
        post :search_items
      end
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  ## 小計を求めるメソッド
  def subtotal
    item.with_tax_price * quantity
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @cart_items = CartItem.all
    @sum = 0
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    if curt_item = current_customer.cart_items.find_by(item_id: params[:cart_itm][:item_id])
      cart_item.number += params[:cart_item][:number].to_i cart_item.save
      flash[:notice] = "カートに商品を追加しました"
      redirect_to cart_items_path
    elsif @cart_item.save
      flash[:notice] = "カートに商品を追加しました"
      redirect_to cart_items_path
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find_by(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def all_destroy
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    flash[:complete]="カートを空にしました"
    redirect_to cart_items_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity, :item_id)
  end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    @cart_items =  current_customer.cart_items.all
    # binding.pry
    @sum = 0
  end

  def create
    # binding.pry
    @cart_item = CartItem.new(cart_item_params)
    if cart_item = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id])
      # binding.pry
       cart_item.quantity += params[:cart_item][:quantity].to_i
       cart_item.save
      flash[:notice] = "カートに商品を追加しました"
      redirect_to cart_items_path
    elsif
     @cart_item.customer_id=current_customer.id
     @cart_item.save
     flash[:notice] = "カートに商品を追加しました"
     redirect_to cart_items_path
    end
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    flash[:notice] = "個数を変更しました"
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:complete]="商品を削除しました"
    redirect_to cart_items_path
  end

  def all_destroy
    @cart_items = current_customer.cart_items
    @cart_items.destroy_all
    flash[:complete]="カートを空にしました"
    redirect_to cart_items_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity, :item_id)
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10">
    <h2>ショッピングカート</h2>
    <div class="col-xs-2">
      <div><%=link_to "カートを空にする", cart_items_all_destroy_path(@cart_items), method: :delete, "data-confirm" => "本当に削除してよろしいでしょうか?", class: "btn btn-danger" %></div>
    </div>
    <div class="row">
    <table class="table table-bordered ">
      <thead class="thead-light">
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @cart_items.each do |cart_item| %>
        <tr>
          <td><%= cart_item.item.name %></td>
          <td><%=(cart_item.item.with_tax_price %></td>
          <td><%= f.select :quantity,  *[1..20] %></td>
          <td>
            <%=(cart_item.subtotal %>
            <% @sum +=  cart_item.subtotal %>
          </td>
          <td><%= link_to "削除する", cart_item_path(cart_item.id), class: "btn btn-danger", method: :delete %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    
    <table class="table table-bordered ">
      <tr>
        <th>合計金額</th>
        <td><%= @sum %></td>
      </tr>
    </table>
    
    <div>
      <%=link_to "買い物を続ける", root_path, class: "btn btn-primary" %>
    </div>
    
    <div>
      <% if @cart_items.count == 0 %>
        <%=link_to "情報入力に進む", cart_items_path, class: "btn btn-success" %>
      <% else %>
        <%=link_to "情報入力に進む", new_order_path, class: "btn btn-success" %>
     <% end %>
    </div>
    
    
    
    </div>
  </div>
</.div>
      